"""Add category column to posts

Revision ID: 271df93ac843
Revises: e287aef93065
Create Date: 2025-11-14 12:28:12.877008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271df93ac843'
down_revision = 'e287aef93065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('news', 'publications', 'tech', 'other', name='category_enum'), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
