"""Initial migration

Revision ID: 29dd12b0d086
Revises: 271df93ac843
Create Date: 2025-11-17 00:14:49.858383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dd12b0d086'
down_revision = '271df93ac843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('news', 'publication', 'tech', 'other', name='category_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('news', 'publication', 'tech', 'other', name='category_enum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
