"""Add created_at with server_default

Revision ID: 55569e38de0e
Revises: 7324bc0c398b
Create Date: 2025-12-04 22:26:19.525805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55569e38de0e'
down_revision = '7324bc0c398b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__alembic_tmp_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'))
    )
    # ### end Alembic commands ###
