"""Add active column to products

Revision ID: 7324bc0c398b
Revises: c9284dde5a71
Create Date: 2025-12-04 22:04:10.899632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean, true

# revision identifiers, used by Alembic.
revision = '7324bc0c398b'
down_revision = 'c9284dde5a71'
branch_labels = None
depends_on = None


def upgrade():
    # Додаємо колонку як NULL
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
    
    # Заповнюємо існуючі рядки значенням True
    op.execute('UPDATE products SET active = 1')  # SQLite використовує 1 для True
    
    # Міняємо колонку на NOT NULL
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('active', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    # ### end Alembic commands ###


# from app.products.models import Product, Category
# iphone = Product(name="iPhone 15", price=999.99)
# db.session.add(iphone)
# db.sesssion.commit()
# laptops = Category(name="Laptops")
# db.session.add(laptops)
# product = Product(name="Gaming Laptop", price=1500.00, active=False,
# category=laptops)
# db.sesssion.commit()
# #перевіримо категорію продукту і які продукти містить категорія laptops
# product.category.name
# laptops.products